version: '3.8'
services:
  go-app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/app:cached
    ports:
      - 8000:8000
    command: /bin/sh -c "while sleep 1000; do :; done"
